### ISSUE TITLE
gpio interrupt 

### ISSUE THREAD

**Issue by RishiBhanot75** [nminaylov/F1C100s_projects#3]
Hi there,
Sorry again today i was struggling with gpio interrupt which does not seems to be working at the moment. I am not sure if i am doing something wrong or may be its not done yet. I saw comment in gpio driver TODO_EINT.
Let me know if you tested it before, i was trying  it as follows :

eint_pin_init(GPIOE_INT,8,EINT_TRG_RISING);
eint_pin_enable(GPIOE_INT,8);

intc_set_irq_handler(IRQ_GPIOE, gpio_porte_irq_handler);
intc_enable_irq(IRQ_GPIOE);

But it never reaches  ISR function.

_void gpio_porte_irq_handler(void)
{
    uint8_t s = eint_pin_get_status(GPIOE_INT,8);
    printf("in gpio_porte_irq_handler...staus=%d\n",s);
    eint_pin_clear_status(GPIOE_INT,8);
}_

Thanks, Rishi

**Comment by nminaylov** [comment]
Yes, I haven't tested EINT functionality yet, but it seems to be done. I'll test and update it soon.
GPIO pin needs to be configured as AF6 for using it as EINT. You can add the following, maybe it will work:
`gpio_pin_init(GPIOE, 8, GPIO_MODE_AF6, GPIO_PULL_DOWN, GPIO_DRV_3);`

**Comment by RishiBhanot75** [comment]
Hi there,
FYI, well i tried with initializing GPIO to AF6 as needed but unfortunately still its not functioning as expected. Basically not getting the interrupt. Anyways i am giving up on this for now. Will move to next peripheral to test. 
Actually we needed i2c and usb device support, so i will start work on that now.

Anyways thanks a lot for a providing great starting point!
Thanks.

**Comment by nminaylov** [comment]
Hi,
I've fixed bug in the INTC driver. Now external interrupts are working.

> I was wondering is it possible to access you through mail ? Maybe you can provide us some commercial help in this project to accelerate things.

Unfortunately, i don't have enought time to continue working on this project. You can contact me via email if you have some questions, but i can't guarantee fast response.

**Comment by RishiBhanot75** [comment]
HI there,
Great ! yes i checked the gpio interrupts and now its working perfectly...
No issues... I understand your prior commitments.
But really i am in pretty good shape now, yesterday i wrote most part of the i2c  driver(basing on xboot) and hopefully should fully functional today.

Thank you so much for prompt  and clear response.
I really appreciate all your help. 
Thanks,Regards, Rishi

**Comment by RishiBhanot75** [comment]
Hi there,
I am trying to jump to FEL mode from my code which is not working, i am wondering if you can help in this.

Basically what i am trying to do is  in your Simple bootloader sample lets says if valid application is not found then i want to jump to FEL mode. I am trying by jumping to 0xffff0020 address.
I tried :
asm volatile("ldr r0, =0xffff0020");
asm volatile("mov pc,r0");

Seems like it jumps i can see on my dmesg :
[57460.002932] usb 1-11.3.2: new full-speed USB device number 63 using xhci_hcd
[57475.418870] usb 1-11.3.2: device descriptor read/64, error -110
[57491.034767] usb 1-11.3.2: device descriptor read/64, error -110

But eventually it fails to setup the usb device.
May be SP also needs to be adjusted, i do not have much deeper understanding in assembly.

Is there any other way where we can programatically jump to FEL mode.
Please let me know once you have some time.

Thanks, Rishi
