### ISSUE TITLE
Using TV in and TV out

### ISSUE THREAD

**Issue by mahdi2001h** [nminaylov/F1C100s_projects#6]
Hi 
i`m trying to use tv out first 
but when i run the code , i have a blank page 
when checked the signal with oscilloscope , the base signal generated but haven't any picture data
in [this video](https://www.youtube.com/watch?v=RpWhTKeg8Yw) a wire is connected to the PA3. its connected to where? its important ?!

**Comment by mahdi2001h** [comment]
yes I running tv_out_test.
I did these steps :
I had a card that contained Linux and u-boot
Then I compile Project tv out_test with the eclipse and copied to the sd card
Then I executed it with the following command:
fatload mmc 0:2 80000000 tv_out_test.bin
go 80000000


before this i tested lcd_test project and it worked properly

**Comment by nminaylov** [comment]
Teseted it, it seems like TCON was initialized to LCD mode by uboot and is't properly deinited after it. 
I've added TCON/DE reset, it should work now

**Comment by mahdi2001h** [comment]
thank you.
now tv in and tv out working correctly
